# @package eval.mytofu.metrics.exact_memorization
defaults:
  - ../../data/datasets@datasets: MYTOFU_forget_eval
  - ../../collator@collators: DataCollatorForSupervisedDatasetwithIndex

handler: exact_memorization
batch_size: ${eval.mytofu.batch_size}

