# @package eval.mytofu.metrics.extraction_strength
defaults:
  - ../../data/datasets@datasets: MYTOFU_forget_eval
  - ../../collator@collators: DataCollatorForSupervisedDatasetwithIndex

handler: extraction_strength
batch_size: ${eval.mytofu.batch_size}

