# @package eval.mytofu.metrics.forget_Q_A_Prob

defaults:
  - ../../data/datasets@datasets: MYTOFU_forget_eval
  - ../../collator@collators: DataCollatorForSupervisedDatasetwithIndex

handler: probability
batch_size: ${eval.mytofu.batch_size}
