# @package eval.mytofu.metrics.mia_min_k_plus_plus
defaults:
  - ../../data/datasets@datasets: TOFU_MIA
  - ../../collator@collators: DataCollatorForSupervisedDatasetwithIndex
batch_size: ${eval.mytofu.batch_size}
k: 0.4
handler: mia_min_k_plus_plus

datasets:
  TOFU_QA_forget:
    args:
      hf_args:
        name: ${eval.mytofu.forget_split}_perturbed
      question_key: ${eval.mytofu.question_key}
  TOFU_QA_holdout:
    args:
      hf_args:
        name: ${eval.mytofu.holdout_split}