# @package eval.mytofu.metrics.mia_reference
defaults:
  - ../../data/datasets@datasets: TOFU_MIA
  - ../../collator@collators: DataCollatorForSupervisedDatasetwithIndex
batch_size: ${eval.mytofu.batch_size}
handler: mia_reference
reference_model_path: ??? # modify appropriately for example open-unlearning/tofu_Llama-3.2-1B-Instruct_retain90

datasets:
  TOFU_QA_forget:
    args:
      hf_args:
        name: ${eval.mytofu.forget_split}_perturbed
      question_key: ${eval.mytofu.question_key}
  TOFU_QA_holdout:
    args:
      hf_args:
        name: ${eval.mytofu.holdout_split}