# @package eval.mytofu.metrics.mia_zlib
defaults:
  - ../../data/datasets@datasets: TOFU_MIA
  - ../../collator@collators: DataCollatorForSupervisedDatasetwithIndex
batch_size: ${eval.mytofu.batch_size}
handler: mia_zlib

datasets:
  TOFU_QA_forget:
    args:
      hf_args:
        name: ${eval.mytofu.forget_split}_perturbed
      question_key: ${eval.mytofu.question_key}
  TOFU_QA_holdout:
    args:
      hf_args:
        name: ${eval.mytofu.holdout_split}