# @package eval.mytofu.metrics.ra_Q_A_PERT_Prob
defaults:
  - ../../data/datasets@datasets: TOFU_QA_ra_pert
  - ../../collator@collators: DataCollatorForSupervisedDatasetwithIndex
  # ^ get default dataset and generation config information

handler: probability
batch_size: ${eval.mytofu.batch_size}