# @package eval.mytofu.metrics.retain_truth_ratio
defaults:
  - .@pre_compute.retain_Q_A_Prob: retain_Q_A_Prob
  - .@pre_compute.retain_Q_A_PERT_Prob: retain_Q_A_PERT_Prob

pre_compute:
  retain_Q_A_Prob:
    access_key: correct
  retain_Q_A_PERT_Prob:
    access_key: wrong

handler: truth_ratio
aggregator: true_better